development:
  bucket: yourapp_dev
  access_key_id: AKIAJHW6EBAVH6HDSM2Q
  secret_access_key: AJHKHJKKJHKHkjsdf+EuXQu5xvingQXY0M+gyYnFGqUJ

test:
  bucket: yourapp_test
  access_key_id: AKIAJHW6EBAVH6HDSM2Q
  secret_access_key: AJHKHJKKJHKHkjsdf+EuXQu5xvingQXY0M+gyYnFGqUJ

production:
  bucket: yourapp_prod
  access_key_id: AFGFHGFHGFGHFHGFHFGHF
  secret_access_key: AJHKHJKKJHKHkjsdf+EuXQu5xvingQXY0M+gyYnFGqUJ